### ISSUE TITLE
Binary not found

### ISSUE THREAD

**Issue by dn3920** [depthsecurity/armory#2]
Multiple packages produce the following error:
``
LinkedInt binary not found. Please explicitly provide path with --binary
``

Could an appropriate work around be posted within the README? or is this a valid issue?

**Comment by fang0654** [comment]
The various tools themselves aren't included in armory - you need to provide a path to them. So for example, with LinkedInt you'd need to clone that repo, and pass the binary to the application with the --binary field. I do have a bunch of documentation to write still before this is released at Blackhat - by then it should be a bit more clear!
