### ISSUE TITLE
--rescan often doesn't work

### ISSUE THREAD

**Issue by sfttw** [depthsecurity/armory#37]
## Expected Behavior
Rerun module on systems that have already been processed

## Actual Behavior
Nothing happens.

## Steps to Reproduce the Problem

  1. Run: armory -m Gowitness -i
  2. Cancel the process before it finishes (ctrl+c)
  3. run: armory -m Gowtiness -i --rescan

## Specifications

  - Python Version: Python 3.7.6
  - Pip packages: argcomplete==1.10.0
backcall==0.1.0
beautifulsoup4==4.8.0
bs4==0.0.1
certifi==2019.6.16
chardet==3.0.4
Click==7.0
colorama==0.4.1
configparser==3.8.1
decorator==4.4.0
depth-armory==1.0.0
dnspython==1.16.0
Flask==1.0.2
future==0.17.1
fuzzywuzzy==0.17.0
geoip2==2.9.0
idna==2.8
ipaddr==2.2.0
ipwhois==1.1.0
ipython==7.7.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.15.0
Jinja2==2.10.3
lxml==4.4.1
MarkupSafe==1.1.1
maxminddb==1.5.1
mysqlclient==1.4.4
netaddr==0.7.19
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
praw==5.4.0
prawcore==0.14.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycurl==7.43.0.3
Pygments==2.4.2
pyparsing==2.4.2
pyperclip==1.7.0
python-docx==0.8.10
python-Levenshtein==0.12.0
pytz==2019.3
requests==2.21.0
requests-file==1.4.3
six==1.12.0
sopel==6.6.9
soupsieve==1.9.2
SQLAlchemy==1.3.6
sqlalchemy-mixins==1.1
termcolor==1.1.0
thready==0.1.5
tld==0.9.3
tldextract==2.2.1
traitlets==4.3.2
typing==3.7.4
update-checker==0.16
urllib3==1.24.3
wcwidth==0.1.7
Werkzeug==0.16.0
wfuzz==2.4
whois==0.8
xmltodict==0.12.0
  - Platform: Fedora 31

**Comment by fang0654** [comment]
That's strange - I use --rescan all the time. Are you only running into this on the Gowitness module?

**Comment by sfttw** [comment]
Ope! I jumped the gun here. This was my fault for not running shodan or aquatone-discover first, so when I ran Gowitness it just did nothing. 

Amazing project by the way, been using it for months now! Gonna close this.
