### ISSUE TITLE
LinkedInt Module Error

### ISSUE THREAD

**Issue by jk-mayne** [depthsecurity/armory#44]
https://github.com/depthsecurity/armory/blob/232ddfe99e762b6fa5a1b75167ed383393ce886a/armory2/armory_main/included/modules/LinkedInt.py#L117

When running the LinkedInt module with options `--top` and `--auto_keyword` I get the following error: 

`  File "/usr/local/lib/python3.7/dist-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/included/modules/LinkedInt.py", line 117, in run
    for user in domain.users
AttributeError: 'BaseDomain' object has no attribute 'users'`

This is after making a regular LinkedInt run and there is a CSV with users already.

**Comment by fang0654** [comment]
Closing because this is an old issue
