### ISSUE TITLE
sqlite3.OperationalError: no such table: armory_main_domain when trying to import domains with Ingestor

### ISSUE THREAD

**Issue by sfttw** [depthsecurity/armory#77]
## Expected Behavior

 Importing domain and IP data directly into the database as well as managing target scoping via the Ingestor module

## Actual Behavior

Armory2 throws an sqlite3 error and exits.

## Steps to Reproduce the Problem

  1.`$ echo 'google.com'>>domains.txt`
  2.`$ armory2 -m Ingestor -d domains.txt -a -p`

> Traceback (most recent call last):
>   File "/home/sfttw/pythons/3.7/bin/armory2", line 33, in <module>
>     sys.exit(load_entry_point('depth-armory==2.0.0', 'console_scripts', 'armory2')())
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 511, in main
>     run_module(Module, mod_args, modules[0])
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 330, in run_module
>     m.run(args)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/includsfttw/modules/Ingestor.py", line 137, in run
>     self.process_domain(line.strip())
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/includsfttw/modules/Ingestor.py", line 164, in process_domain
>     "passive_scope": self.passive_scope,
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 581, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
>     num = len(clone)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
>     self._fetch_all()
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 51, in __iter__
>     results = compiler.execute_sql(chunksfttw_fetch=self.chunksfttw_fetch, chunk_size=self.chunk_size)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.OperationalError: no such table: armory_main_domain

## Specifications

  - Python Version: Python 3.7.8
  - Pip packages: `argcomplete==1.12.3
asttokens==2.0.5
backcall==0.2.0
beautifulsoup4==4.10.0
black==21.12b0
bs4==0.0.1
certifi==2021.10.8
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
configparser==5.2.0
decorator==5.1.0
depth-armory==1.0.0
dnspython==2.0.0
executing==0.8.2
filelock==3.4.2
fuzzywuzzy==0.18.0
greenlet==1.1.2
idna==3.3
importlib-metadata==4.10.0
ipaddr==2.2.0
ipwhois==1.2.0
ipython==8.0.0b1
jedi==0.18.1
Jinja2==3.0.3
lxml==4.7.1
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mypy-extensions==0.4.3
mysqlclient==2.1.0
netaddr==0.8.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.4.1
prompt-toolkit==3.0.24
ptyprocess==0.7.0
pure-eval==0.2.1
Pygments==2.11.1
pyperclip==1.8.2
python-docx==0.8.11
python-Levenshtein==0.12.2
requests==2.26.0
requests-file==1.5.1
six==1.16.0
soupsieve==2.3.1
SQLAlchemy==1.4.29
sqlalchemy-mixins==1.5
stack-data==0.1.3
termcolor==1.1.0
thready==0.1.5
tld==0.12.6
tldextract==3.1.2
tomli==1.2.3
traitlets==5.1.1
typed-ast==1.5.1
typing_extensions==4.0.1
urllib3==1.26.7
wcwidth==0.2.5
whois==0.9.13
xmltodict==0.12.0
zipp==3.7.0`
  - Platform: OpenSuse Leap 15.3 (also tested on the latest versions of Fedora and MacOS)

**Comment by fang0654** [comment]
Thanks for the bug report! When you first run it, you need to run `armory2-manage migrate`. This will create the database and all of the tables
On Jan 1, 2022 1:07 AM, sailing faster than the wind wrote:


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or on clicking links from unknown senders.

## Expected Behavior

 Importing domain and IP data directly into the database as well as managing target scoping via the Ingestor module

## Actual Behavior

Armory2 throws an sqlite3 error and exits.

## Steps to Reproduce the Problem

  1.`$ echo 'google.com'>>domains.txt`
  2.`$ armory2 -m Ingestor -d domains.txt -a -p`

> Traceback (most recent call last):
>   File "/home/sfttw/pythons/3.7/bin/armory2", line 33, in <module>
>     sys.exit(load_entry_point('depth-armory==2.0.0', 'console_scripts', 'armory2')())
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 511, in main
>     run_module(Module, mod_args, modules[0])
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 330, in run_module
>     m.run(args)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/includsfttw/modules/Ingestor.py", line 137, in run
>     self.process_domain(line.strip())
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/includsfttw/modules/Ingestor.py", line 164, in process_domain
>     "passive_scope": self.passive_scope,
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 581, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
>     num = len(clone)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
>     self._fetch_all()
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 51, in __iter__
>     results = compiler.execute_sql(chunksfttw_fetch=self.chunksfttw_fetch, chunk_size=self.chunk_size)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/sfttw/pythons/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.OperationalError: no such table: armory_main_domain

## Specifications

  - Python Version: Python 3.7.8
  - Pip packages: `argcomplete==1.12.3
asttokens==2.0.5
backcall==0.2.0
beautifulsoup4==4.10.0
black==21.12b0
bs4==0.0.1
certifi==2021.10.8
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
configparser==5.2.0
decorator==5.1.0
depth-armory==1.0.0
dnspython==2.0.0
executing==0.8.2
filelock==3.4.2
fuzzywuzzy==0.18.0
greenlet==1.1.2
idna==3.3
importlib-metadata==4.10.0
ipaddr==2.2.0
ipwhois==1.2.0
ipython==8.0.0b1
jedi==0.18.1
Jinja2==3.0.3
lxml==4.7.1
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mypy-extensions==0.4.3
mysqlclient==2.1.0
netaddr==0.8.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.4.1
prompt-toolkit==3.0.24
ptyprocess==0.7.0
pure-eval==0.2.1
Pygments==2.11.1
pyperclip==1.8.2
python-docx==0.8.11
python-Levenshtein==0.12.2
requests==2.26.0
requests-file==1.5.1
six==1.16.0
soupsieve==2.3.1
SQLAlchemy==1.4.29
sqlalchemy-mixins==1.5
stack-data==0.1.3
termcolor==1.1.0
thready==0.1.5
tld==0.12.6
tldextract==3.1.2
tomli==1.2.3
traitlets==5.1.1
typed-ast==1.5.1
typing_extensions==4.0.1
urllib3==1.26.7
wcwidth==0.2.5
whois==0.9.13
xmltodict==0.12.0
zipp==3.7.0`
  - Platform: OpenSuse Leap 15.3 (also tested on the latest versions of Fedora and MacOS)


-- 
Reply to this email directly or view it on GitHub:
https://github.com/depthsecurity/armory/issues/77

**Comment by sfttw** [comment]
That fixed it. Thanks!
